{% set name = "fann2" %}
{% set version = "1.1.2" %}

package:
  name: 'py-{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url:  https://github.com/FutureLinkCorporation/{{ name }}/archive/{{ version }}.tar.gz
  'sha256': '0f2ae9e14630d4d652ffb58f9239ca488e5c15c38e9302f204c24d8c2f7cf0d8'
  patches:
    - setup.py.patch

build:
  number: 1004
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - fann2
    - swig
    - pip
  run:
    - python
    - fann2

test:
  imports:
    - fann2

about:
  home: https://github.com/FutureLinkCorporation/fann2
  license: LGPL-2.1
  license_family: LGPL
  license_file: 'LICENSE'
  summary: Fast Artificial Neural Network Library (fann) python bindings.
  description: |
    Python bindings for Fast Artificial Neural Networks (FANN) library that
    implements multilayer artificial neural networks with support for both
    fully-connected and sparsely-connected networks. It includes a framework for
    easy handling of training data sets. It is easy to use, versatile, well-
    documented, and fast.

extra:
  recipe-maintainers:
    - smithsp
