travis:
  secure:
    BINSTAR_TOKEN: f8hiSQm3jDih06NdxkPuVXkUBaDYWTBIIXYCtoiixac508+GTN1EJvuNfPifqi6Sp9cbKWMGnh6S8/Slrwv2OORAZcEz0HVHSl2cgHO/V3yyuwax5ZWpa2F87p2+lb4E32jPGkmv8oJdqEovJlkW4lzh6pY5qDHjP/u5sGsIT5XKgDr4qEybs5X5fy6H/+L1KeomVq7CUmaEsUMwe116lK4j5IHJuz1R3S2R8Pgl7EGT5iDRVGcI7JnFSxLrxwW0e8SvHz3PYIUV5NQEMElmLxl9g6+j1uWwkvMwFUPDM4IlSi/eO1mup3y1GcX0nh0pWaKo4U8tJcpvoV6EKfzUpbeYLh6Q9tiH5CIzY3WNZtdWW2NCybe0fErquePj9vVQKND0nEEAlBNNTmXcTiyGSHN4MZNskUfX8FUNhHx/5RzDmQ0zMFPGsjG2uXs/0NM9atGaK9c4rCNxMqkZxPyGC3V7hDDZhzAdkKn3sS/3YOmS+LtFxLXYIhpiA+IajK6yMMUpLHf8Ndpw4JDdRgK6R2QW/kS5+bRrqCwi95K8uq42+YnG498oQzeMFK6fe+ekEim3S6OMGwBk5aGdFP4OhDJ2gMWfEZNmXl+OsZzr6lysUbsMaNuFQznm9OzMsCfo7zKrSBWr3nkmk9ZtLHjuEwBwVH16aHRZWtyUTBjWUEQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
