travis:
  secure:
    BINSTAR_TOKEN: iDq3pWBcrQ3BzqnEg4yo6CK+J2oARcRStc5n12ILAyDLEMLD7WvzYoTfSLSKXWmCCTRUfNeTizWyDTzFiOoGT1CZWx9SCh7vjk7BhBc68vZVGFCloXvpXPm1KSul7k6V03ztOYk0XAt2JF+XXFqMhdvQ84A1+f/Z+pGG5LTCuFtET2Ux4Rq61ZZdJ/1WDw6JsQnPu5iOw5QSRRXi1zLaimrIPphKBfBD2D4Zx4DuuNQu+U6NVpf9Q1WV6y6dopc9VzsjilhCiPhj4Kp3u5tauYm1nAw2a9OBxLoA5vvOG7ojS4Oi5iRDAGfDkV8V6cZ+La8qYJyybUb1zi9F79R1MQT9rnYXSe8A4C4ytiI2KOdKEOPQjFOw/+Nw9Vx3KPUFgjCmGy14SEUeVCLfZYod80IUbgjAy7Dm9LPAFTAKYFqZI9pe76J7j7LY3GQqrTvV3qH+l1Ste59304CRqJ2gcPPv6sez9XhZL5++0GRsBBqa/KUjSGHvyh/GUanCigjIy0rseuHt7adtNM/7QwuOqTPZdoXr5Jq2cw8Puc4BtVdyNtwUEykZhZ7urtbNI7jCeePoDq3iM5D2IoJt+h2TnZ13mSPHbDs8zpP9VgP21rRdAoxOh9rFBtEjz4L4OmauiVLGvDWYWW6/gGdT2Mor7Yv69lHbrFWQqS7gRynQSKc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
